config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #static templates
	# get "/templates/*template" => "templates#show"
	get "/*template" => "templates#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  def show
    if valid_template?
      render template: "templates/#{params[:template]}/index.html"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private
  def valid_template?
    File.exist?(Pathname.new(Rails.root + "app/views/templates/#{params[:template]}/index.html"))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HtmlTemplates</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/templates/_form.html.erb
<%= form_with(model: template, local: true) do |form| %>
  <% if template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<h1>Editing Template</h1>

<%= render 'form', template: @template %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Templates</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @templates.each do |template| %>
      <tr>
        <td><%= link_to 'Show', template %></td>
        <td><%= link_to 'Edit', edit_template_path(template) %></td>
        <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Template', new_template_path %>

app/views/templates/new.html.erb
<h1>New Template</h1>

<%= render 'form', template: @template %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>